name: AWS TEMPLATE
on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string
      location:
        required: true
        type: string # use ${{ inputs.location }}
    secrets: 
        TF_TOKEN:
          required: true

jobs:
  myDeployment:
    runs-on: ubuntu-latest
    #environment: dev # need pro/enterprise to use environments...
    steps:

    - name: Checkout  
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        # terraform_version: 0.13.0
        cli_config_credentials_token: ${{ secrets.TF_TOKEN }}

    - name: move dir
      id: cd
      run: cd ${GITHUB_WORKSPACE}/tf

    - name: Terraform Format
      id: fmt
      run: cd ${GITHUB_WORKSPACE}/tf && terraform fmt -check

    - name: Terraform Init
      id: init
      run: cd ${GITHUB_WORKSPACE}/tf && terraform init

    - name: Terraform Validate
      id: validate
      run: cd ${GITHUB_WORKSPACE}/tf && terraform validate -no-color

    - name: Terraform Plan
      id: plan
      #if: github.event_name == 'pull_request'
      run: cd ${GITHUB_WORKSPACE}/tf && terraform plan -no-color
      #continue-on-error: true

    # - name: Terraform Apply
    #   if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    #   run: terraform apply -auto-approve
