name: Azure Backend Pipeline
on:
  workflow_dispatch:
jobs:
  myDeployment:
    uses: samuelhornby/githubactions/.github/workflows/template.yml@main
    with:
      env: 'landingzone'
      envCode: 'lz'
      location: 'australiaeast'
      azureRegionCode: 'aue'
      AZURE_SUBSCRIPTION: '58a6d4a5-183f-4489-967e-331035386e05'
    secrets: 
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}