name: Azure Pipeline
on:
  workflow_dispatch:
jobs:
  myDeployment:
    uses: samuelhornby/githubactions/.github/workflows/template.yml@main
    with:
      env: 'landingzone'
      envCode: 'lz'
      location: 'australiaeast'
      azureRegionCode: 'aue'
    secrets: 
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}