name: GitHub Actions
on: [push]
jobs:
  myDeployment:
    uses: .github/workflows/workflow-templates/template.yml@main
    with:
      env: 'dev'
      location: 'here'
    # secrets: # probably wouldn't use this, just get from KV
    #   vmPassword: ${{ secrets.vmPassword }}